source 'https://rubygems.org'

# This is separate gemfile for building docker image that has all plugins 
# for kubernetes log collection agent
# List all required gems here and install via bundler to resolve dependencies
gem "fluentd", "=1.9.1" 
gem "fluent-plugin-systemd", "=1.0.2"
gem "fluent-plugin-concat", "=2.4.0"
gem "fluent-plugin-prometheus", "=1.7.0"
gem "fluent-plugin-jq", "=0.5.1"
gem "fluent-plugin-kubernetes_metadata_filter", "=2.4.5"
gem "oj", "=3.10.2"
gem 'multi_json', '~> 1.13'
gem 'net-http-persistent', '~> 3.1'
gem 'openid_connect', '~> 1.1.8'
gem 'prometheus-client', '< 0.10.0'
gem 'activesupport', '~> 5.2'
gem 'http_parser.rb', '=0.5.3'

gem 'fluent-plugin-splunk-hec', path: 'gem/'